// api/send-email.js — Vercel serverless function
// Sends the Stage 1 results email (v2 template) via Resend.
//
// v2 rewrite: the template is now generated by lib/email-templates.js and
// matches the design preview (fw_email_design_preview.html). Copy is
// verbatim from "Faithful Witness — Stage 1 Results Email v2" (Drive).
//
// The API contract is intentionally compatible with the prior caller in
// index.html. Either of these payload shapes works:
//
//   New (preferred):
//     { email, firstName, profileKey, participantId }
//
//   Legacy (still accepted — what index.html sends today):
//     { email, name, profileType, participantId? }
//
// Anything else in the payload (narrativeHTML, resources, continueUrl) is
// ignored; v2 doesn't need it. The wire format is unchanged.

'use strict';

const { renderStage1Email, PROFILE_KEYS } = require('../lib/email-templates.js');

const RESEND_API_KEY = process.env.RESEND_API_KEY;
const FROM_EMAIL     = 'Faithful Witness <discernment@faithfulwitness.us>';

function pickFirstName(payload) {
  const raw = (payload.firstName || payload.name || '').trim();
  if (!raw) return 'friend';
  return raw.split(/\s+/)[0];
}

function pickProfileKey(payload) {
  // Accept either profileKey (new) or profileType (legacy). Both store the
  // canonical key. Fall back to open_explorer if anything else.
  const k = (payload.profileKey || payload.profileType || '').trim();
  return PROFILE_KEYS.indexOf(k) >= 0 ? k : 'open_explorer';
}

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const data = typeof req.body === 'string' ? JSON.parse(req.body) : (req.body || {});
    if (!data.email) return res.status(400).json({ error: 'No email provided' });

    const firstName     = pickFirstName(data);
    const profileKey    = pickProfileKey(data);
    const participantId = data.participantId || data.participant_id || '';

    const { subject, html } = renderStage1Email({ firstName, profileKey, participantId });

    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type':  'application/json',
        'Authorization': `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from:    FROM_EMAIL,
        to:      [data.email],
        subject: subject,
        html:    html,
      }),
    });

    const result = await response.json().catch(() => ({}));

    if (!response.ok) {
      // eslint-disable-next-line no-console
      console.error('Resend error:', result);
      return res.status(500).json({ success: false, error: (result && result.message) || 'Email send failed' });
    }

    return res.status(200).json({ success: true, id: result.id || null });
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error('send-email error:', err);
    return res.status(500).json({ success: false, error: 'Server error' });
  }
};
